---
title: ATC Chatbot
timezone: Europe/Amsterdam
collections:
  bots:
    title: Bots
    permalink: /bots/:title/
    output: true
defaults:
- scope:
    path: ''
    type: bots
  values:
    layout: bot
image_src: "/assets/img/image_src.png"
logo: "/assets/img/image_src.png"
keywords: Polyism Studio Sem Postma Echo Sierra Studio Web Software Code Programming
  Hub
exclude:
- vendor
description: Web, app and tooling development and graphic design studio. View all
  websites made by Echo Sierra Studio and contact us if your interested.
theme_color: "#fb5353"
sass:
  style: compressed
  sass_dir: _sass
url: https://atc-chatbot.esstudio.site
enforce_ssl: atc-chatbot.esstudio.site
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
author: Sem Postma
designer: Sem Postma
lang: en
google_analytics: 
